local LSM = LibStub("LibSharedMedia-3.0") 

-- COUNTDOWN
LSM:Register("sound", "|cFFFF80001|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\1.ogg]])
LSM:Register("sound", "|cFFFF80002|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\2.ogg]])
LSM:Register("sound", "|cFFFF80003|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\3.ogg]])
LSM:Register("sound", "|cFFFF80004|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\4.ogg]])
LSM:Register("sound", "|cFFFF80005|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\5.ogg]])
LSM:Register("sound", "|cFFFF80006|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\6.ogg]])
LSM:Register("sound", "|cFFFF80007|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\7.ogg]])
LSM:Register("sound", "|cFFFF80008|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\8.ogg]])
LSM:Register("sound", "|cFFFF80009|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\9.ogg]])
LSM:Register("sound", "|cFFFF800010|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\10.ogg]])

-- RAID MARKERS
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\star.ogg]])
LSM:Register("sound", "|cFFD2D153Yellow|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\yellow.ogg]])
LSM:Register("sound", "|cFFD2D153Move to yellow|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_yellow.ogg]])
LSM:Register("sound", "|cFFD2D153Move to star|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_star.ogg]])

LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\circle.ogg]])
LSM:Register("sound", "|cFFE17D03Orange|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\orange.ogg]])
LSM:Register("sound", "|cFFE17D03Move to orange|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_orange.ogg]])
LSM:Register("sound", "|cFFE17D03Move to circle|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_circle.ogg]])

LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\diamond.ogg]])
LSM:Register("sound", "|cFFCA4AD5Purple|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\purple.ogg]])
LSM:Register("sound", "|cFFCA4AD5Move to purple|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_purple.ogg]])
LSM:Register("sound", "|cFFCA4AD5Move to diamond|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_diamond.ogg]])

LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\triangle.ogg]])
LSM:Register("sound", "|cFF20B717Green|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\green.ogg]])
LSM:Register("sound", "|cFF20B717Move to green|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_green.ogg]])
LSM:Register("sound", "|cFF20B717Move to triangle|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_triangle.ogg]])

LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\moon.ogg]])
LSM:Register("sound", "|cFFFFFFFFMove to moon|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_moon.ogg]])

LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\square.ogg]])
LSM:Register("sound", "|cFF02BEE9Blue|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\blue.ogg]])
LSM:Register("sound", "|cFF02BEE9Move to blue|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_blue.ogg]])
LSM:Register("sound", "|cFF02BEE9Move to square|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_square.ogg]])

LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cross.ogg]])
LSM:Register("sound", "|cFFEC5B41Red|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\red.ogg]])
LSM:Register("sound", "|cFFEC5B41Move to red|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_red.ogg]])
LSM:Register("sound", "|cFFEC5B41Move to cross|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_cross.ogg]])

LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\skull.ogg]])
LSM:Register("sound", "|cFFFFFFFFMove to skull|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_skull.ogg]])

-- CARDINAL DIRECTIONS
LSM:Register("sound", "|cFFFF8000North|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\north.ogg]])
LSM:Register("sound", "|cFFFF8000East|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\east.ogg]])
LSM:Register("sound", "|cFFFF8000South|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\south.ogg]])
LSM:Register("sound", "|cFFFF8000West|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\west.ogg]])
LSM:Register("sound", "|cFFFF8000Northeast|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\northeast.ogg]])
LSM:Register("sound", "|cFFFF8000Northwest|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\northwest.ogg]])
LSM:Register("sound", "|cFFFF8000Southeast|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\southeast.ogg]])
LSM:Register("sound", "|cFFFF8000Southwest|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\southwest.ogg]])


-- RELATIVE DIRECTIONS
LSM:Register("sound", "|cFFFF8000Left|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\left.ogg]])
LSM:Register("sound", "|cFFFF8000Right|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\right.ogg]])

LSM:Register("sound", "|cFFFF8000Center|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\center.ogg]])
LSM:Register("sound", "|cFFFF8000Center left|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\centerleft.ogg]])
LSM:Register("sound", "|cFFFF8000Center right|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\centerright.ogg]])

LSM:Register("sound", "|cFFFF8000Front|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\front.ogg]])
LSM:Register("sound", "|cFFFF8000Front left|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\frontleft.ogg]])
LSM:Register("sound", "|cFFFF8000Front right|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\frontright.ogg]])

LSM:Register("sound", "|cFFFF8000Back|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\back.ogg]])
LSM:Register("sound", "|cFFFF8000Back left|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\back left.ogg]])
LSM:Register("sound", "|cFFFF8000Back right|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\back right.ogg]])

-- GROUPINGS
LSM:Register("sound", "|cFFFF8000Group 1|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\group1.ogg]])
LSM:Register("sound", "|cFFFF8000Group 2|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\group2.ogg]])
LSM:Register("sound", "|cFFFF8000Group 3|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\group3.ogg]])
LSM:Register("sound", "|cFFFF8000Group 4|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\group4.ogg]])
LSM:Register("sound", "|cFFFF8000Group 5|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\group5.ogg]])

LSM:Register("sound", "|cFFFF8000Interrupt 1|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt_1.ogg]])
LSM:Register("sound", "|cFFFF8000Interrupt 2|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt_2.ogg]])
LSM:Register("sound", "|cFFFF8000Interrupt 3|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt_3.ogg]])
LSM:Register("sound", "|cFFFF8000Interrupt 4|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt_4.ogg]])
LSM:Register("sound", "|cFFFF8000Interrupt 5|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt_5.ogg]])

-- PHASES
LSM:Register("sound", "|cFFFF8000Phase one|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\phase_one.ogg]])
LSM:Register("sound", "|cFFFF8000Phase two|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\phase_two.ogg]])
LSM:Register("sound", "|cFFFF8000Phase three|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\phase_three.ogg]])
LSM:Register("sound", "|cFFFF8000Phase four|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\phase_four.ogg]])
LSM:Register("sound", "|cFFFF8000Phase five|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\phase_five.ogg]])

LSM:Register("sound", "|cFFFF8000Intermission|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\intermission.ogg]])
LSM:Register("sound", "|cFFFF8000Phase change|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\phase_change.ogg]])
LSM:Register("sound", "|cFFFF00FFSwitch Phase|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\switch_phase.ogg]])
LSM:Register("sound", "|cFFFF00FFTransition|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\transition.ogg]])
LSM:Register("sound", "|cFFFF8000Transition phase|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\transition_phase.ogg]])

-- DPS Timings
LSM:Register("sound", "|cFFFF00FFHard DPS|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dpshard.ogg]])
LSM:Register("sound", "|cFFFF00FFMore DPS|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dpsmore.ogg]])
LSM:Register("sound", "|cFFFF00FFSlow DPS|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dpsslow.ogg]])
LSM:Register("sound", "|cFFFF00FFStop DPS|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dpsstop.ogg]])

-- Common instructions
LSM:Register("sound", "|cFFFF00FFStop|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stop.ogg]])
LSM:Register("sound", "|cFFFF00FFGo|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\go.ogg]])
LSM:Register("sound", "|cFFFF00FFIn|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\in.ogg]])
LSM:Register("sound", "|cFFFF00FFOut|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\out.ogg]])

-- EVERYTHING ELSE, ALPHABETICAL (except for spell name acronyms)
LSM:Register("sound", "|cFFFF00FFAdd|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\add.ogg]])
LSM:Register("sound", "|cFFFF00FFAdds|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\adds.ogg]])
LSM:Register("sound", "|cFFFF00FFAdds Incoming|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\addsincoming.ogg]])
LSM:Register("sound", "|cFFFF00FFAOE|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\aoe.ogg]])
LSM:Register("sound", "|cFFFF00FFAssist|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\assist.ogg]])
LSM:Register("sound", "|cFFFF00FFAvoid|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\avoid.ogg]])
LSM:Register("sound", "|cFFFF00FFArtillery|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\artillery.ogg]])
LSM:Register("sound", "|cFFFF00FFAttack totem|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\attacktotem.ogg]])
LSM:Register("sound", "|cFFFF00FFBack up|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\back_up.ogg]])
LSM:Register("sound", "|cFFFF00FFBehind Boss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\behind_boss.ogg]])
LSM:Register("sound", "|cFFFF00FFBig Add|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\big_add.ogg]])
LSM:Register("sound", "|cFFFF00FFBlaze|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\blaze.ogg]])
LSM:Register("sound", "|cFFFF00FFBleed|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\bleed.ogg]])
LSM:Register("sound", "|cFFFF00FFBlessing of sacrifice|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\blessing_of_sacrifice.ogg]])
LSM:Register("sound", "|cFFFF00FFSac|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\sac.ogg]])
LSM:Register("sound", "|cFFFF00FFBloodlust|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\bloodlust.ogg]])
LSM:Register("sound", "|cFFFF00FFBomb on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\bombyou.ogg]])
LSM:Register("sound", "|cFFFF00FFBoss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\boss.ogg]])
LSM:Register("sound", "|cFFFF00FFBreak|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\break.ogg]])
LSM:Register("sound", "|cFFFF00FFBreak chain|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\breakchain.ogg]])
LSM:Register("sound", "|cFFFF00FFBreak LOS|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\breaklos.ogg]])
LSM:Register("sound", "|cFFFF00FFBreath incoming|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\breath_incoming.ogg]])
LSM:Register("sound", "|cFFFF00FFBuff|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\buff.ogg]])
LSM:Register("sound", "|cFFFF00FFCage|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cage.ogg]])
LSM:Register("sound", "|cFFFF00FFCatch balls|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\catch_balls.ogg]])
LSM:Register("sound", "|cFFFF00FFCrowd control|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\crowdcontrol.ogg]])
LSM:Register("sound", "|cFFFF00FFCC|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cc.ogg]])
LSM:Register("sound", "|cFFFF00FFCooldown|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cooldown.ogg]])
LSM:Register("sound", "|cFFFF00FFCD|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cd.ogg]])
LSM:Register("sound", "|cFFFF00FFChain|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\chain.ogg]])
LSM:Register("sound", "|cFFFF00FFChange color|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\change_color.ogg]])
LSM:Register("sound", "|cFFFF00FFCharge|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\charge.ogg]])
LSM:Register("sound", "|cFFFF00FFCharging move|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\chargemove.ogg]])
LSM:Register("sound", "|cFFFF00FFClear|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\clear.ogg]])
LSM:Register("sound", "|cFFFF00FFCleave|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cleave.ogg]])
LSM:Register("sound", "|cFFFF00FFCollect|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\collect.ogg]])
LSM:Register("sound", "|cFFFF00FFCrusher|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\crusher.ogg]])
LSM:Register("sound", "|cFFFF00FFCurse|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\curse.ogg]])
LSM:Register("sound", "|cFFFF00FFDance|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dance.ogg]])
LSM:Register("sound", "|cFFFF00FFDanger close|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\danger_close.ogg]])
LSM:Register("sound", "|cFFFF00FFDebuff|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\debuff.ogg]])
LSM:Register("sound", "|cFFFF00FFDefensive|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\defensive.ogg]])
LSM:Register("sound", "|cFFFF00FFDemolisher|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\demolisher.ogg]])
LSM:Register("sound", "|cFFFF00FFDisease|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\disease.ogg]])
LSM:Register("sound", "|cFFFF00FFDispel|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dispel.ogg]])
LSM:Register("sound", "|cFFFF00FFDispel boss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dispel_boss.ogg]])
LSM:Register("sound", "|cFFFF00FFDodge|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dodge.ogg]])
LSM:Register("sound", "|cFFFF00FFDon\'t|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dont.ogg]])
LSM:Register("sound", "|cFFFF00FFDon\'t move|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dont_move.ogg]])
LSM:Register("sound", "|cFFFF00FFDoT|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dot.ogg]])
LSM:Register("sound", "|cFFFF00FFDrop|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\drop.ogg]])
LSM:Register("sound", "|cFFFF00FFEnfeebling roar|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\enfeebling_roar.ogg]])
LSM:Register("sound", "|cFFFF00FFEnrage|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\enrage.ogg]])
LSM:Register("sound", "|cFFFF00FFEnter|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\enter.ogg]])
LSM:Register("sound", "|cFFFF00FFEscort|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\escort.ogg]])
LSM:Register("sound", "|cFFFF00FFExit|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\exit.ogg]])
LSM:Register("sound", "|cFFFF00FFFear incoming|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\fear_incoming.ogg]])
LSM:Register("sound", "|cFFFF00FFFeet|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\feet.ogg]])
LSM:Register("sound", "|cFFFF00FFFind shelter|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\find_shelter.ogg]])
LSM:Register("sound", "|cFFFF00FFFind shield|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\find_shield.ogg]])
LSM:Register("sound", "|cFFFF00FFFixate|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\fixate.ogg]])
LSM:Register("sound", "|cFFFF00FFFocus|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\focus.ogg]])
LSM:Register("sound", "|cFFFF00FFFrenzy|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\frenzy.ogg]])
LSM:Register("sound", "|cFFFF00FFFrontal|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\frontal.ogg]])
LSM:Register("sound", "|cFFFF00FFGate|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\gate.ogg]])
LSM:Register("sound", "|cFFFF00FFGather|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\gather.ogg]])
LSM:Register("sound", "|cFFFF00FFGather item|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\gather_item.ogg]])

LSM:Register("sound", "|cFFFF00FFHeal to full|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\healtofull.ogg]])
LSM:Register("sound", "|cFFFF00FFHeal CD|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\healcd.ogg]])
LSM:Register("sound", "|cFFFF00FFHealing Cooldown|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\healing_cooldown.ogg]])
LSM:Register("sound", "|cFFFF00FFHelp soak|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\help_soak.ogg]])
LSM:Register("sound", "|cFFFF00FFHelp spirit|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\help_spirit.ogg]])
LSM:Register("sound", "|cFFFF00FFHeroism|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\heroism.ogg]])
LSM:Register("sound", "|cFFFF00FFHide|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\hide.ogg]])
LSM:Register("sound", "|cFFFF00FFHigh energy|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\high_energy.ogg]])
LSM:Register("sound", "|cFFFF00FFHigh stacks|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\high_stacks.ogg]])
LSM:Register("sound", "|cFFFF00FFImmunity|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\immunity.ogg]])
LSM:Register("sound", "|cFFFF00FFIncoming debuff|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\incoming_debuff.ogg]])

LSM:Register("sound", "|cFFFF00FFInnervate|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\innervate.ogg]])
LSM:Register("sound", "|cFFFF00FFInterrupt|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt.ogg]])
LSM:Register("sound", "|cFFFF00FFInvisibility|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\invisibility.ogg]])
LSM:Register("sound", "|cFFFF00FFJump|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\jump.ogg]])
LSM:Register("sound", "|cFFFF00FFJump now|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\jump_now.ogg]])
LSM:Register("sound", "|cFFFF00FFJust don\'t|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\just_dont.ogg]])
LSM:Register("sound", "|cFFFF00FFKeep jumping|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\keep_jumping.ogg]])
LSM:Register("sound", "|cFFFF00FFKeep moving|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\keep_moving.ogg]])
LSM:Register("sound", "|cFFFF00FFKick|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\kick.ogg]])
LSM:Register("sound", "|cFFFF00FFKill big add|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\kill_big_add.ogg]])
LSM:Register("sound", "|cFFFF00FFKite|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\kite.ogg]])
LSM:Register("sound", "|cFFFF00FFKnock|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\knock.ogg]])
LSM:Register("sound", "|cFFFF00FFKnockback|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\knockback.ogg]])
LSM:Register("sound", "|cFFFF00FFLaser on you, run|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\laser_run.ogg]])
LSM:Register("sound", "|cFFFF00FFLine apart|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\line_apart.ogg]])
LSM:Register("sound", "|cFFFF00FFLine gather|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\line_gather.ogg]])
LSM:Register("sound", "|cFFFF00FFLine of Sight|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\line_of_sight.ogg]])
LSM:Register("sound", "|cFFFF00FFLinked|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\linked.ogg]])
LSM:Register("sound", "|cFFFF00FFMacro|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\macro.ogg]])
LSM:Register("sound", "|cFFFF00FFMagic|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\magic.ogg]])
LSM:Register("sound", "|cFFFF00FFMain|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\main.ogg]])
LSM:Register("sound", "|cFFFF00FFMarked for death|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\markedfordeath.ogg]])
LSM:Register("sound", "|cFFFF00FFMC|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\mc.ogg]])
LSM:Register("sound", "|cFFFF00FFMind control|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\mindcontrol.ogg]])
LSM:Register("sound", "|cFFFF00FFMelee|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\melee.ogg]])
LSM:Register("sound", "|cFFFF00FFMeteor run|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\meteorrun.ogg]])
LSM:Register("sound", "|cFFFF00FFMove boss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\moveboss.ogg]])
LSM:Register("sound", "|cFFFF00FFMove to boss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_boss.ogg]])
LSM:Register("sound", "|cFFFF00FFMove to melee|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_melee.ogg]])
LSM:Register("sound", "|cFFFF00FFMove to mobs|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_mobs.ogg]])
LSM:Register("sound", "|cFFFF00FFMove to pillar|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_pillar.ogg]])
LSM:Register("sound", "|cFFFF00FFMove to pool|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_pool.ogg]])
LSM:Register("sound", "|cFFFF00FFMove to tank|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_tank.ogg]])
LSM:Register("sound", "|cFFFF00FFNegative|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\negative.ogg]])
LSM:Register("sound", "|cFFFF00FFNext|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\next.ogg]])
LSM:Register("sound", "|cFFFF00FFNuke|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\nuke.ogg]])
LSM:Register("sound", "|cFFFF00FFOrb|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\orb.ogg]])
LSM:Register("sound", "|cFFFF00FFOverlap|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\overlap.ogg]])
LSM:Register("sound", "|cFFFF00FFPain Suppression|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pain_suppression.ogg]])
LSM:Register("sound", "|cFFFF00FFPS|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\ps.ogg]])
LSM:Register("sound", "|cFFFF00FFPass Debuff|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pass_debuff.ogg]])
LSM:Register("sound", "|cFFFF00FFPersonal CD|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\personal_cd.ogg]])
LSM:Register("sound", "|cFFFF00FFPhysical|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\physical.ogg]])
LSM:Register("sound", "|cFFFF00FFPower Infusion|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\power_infusion.ogg]])
LSM:Register("sound", "|cFFFF00FFPI|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pi.ogg]])
LSM:Register("sound", "|cFFFF00FFPoison|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\poison.ogg]])
LSM:Register("sound", "|cFFFF00FFPolarity shift|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\polarity_shift.ogg]])
LSM:Register("sound", "|cFFFF00FFPositive|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\positive.ogg]])
LSM:Register("sound", "|cFFFF00FFPotions|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\potions.ogg]])
LSM:Register("sound", "|cFFFF00FFPots|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pots.ogg]])
LSM:Register("sound", "|cFFFF00FFPull|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pull.ogg]])
LSM:Register("sound", "|cFFFF00FFPull adds out|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pulladdsout.ogg]])
LSM:Register("sound", "|cFFFF00FFPulling in|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pulling_in.ogg]])
LSM:Register("sound", "|cFFFF00FFPulverize|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pulverize.ogg]])
LSM:Register("sound", "|cFFFF00FFPush|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\push.ogg]])
LSM:Register("sound", "|cFFFF00FFPushback incoming|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pushback_incoming.ogg]])
LSM:Register("sound", "|cFFFF00FFQuake|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\quake.ogg]])
LSM:Register("sound", "|cFFFF00FFRange|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\range.ogg]])
LSM:Register("sound", "|cFFFF00FFRange 5|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\range5.ogg]])
LSM:Register("sound", "|cFFFF00FFReady|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\ready.ogg]])
LSM:Register("sound", "|cFFFF00FFReady to interrupt|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\ready_interrupt.ogg]])
LSM:Register("sound", "|cFFFF00FFReflect|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\reflect.ogg]])
LSM:Register("sound", "|cFFFF00FFRing|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\ring.ogg]])
LSM:Register("sound", "|cFFFF00FFRoot|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\root.ogg]])
LSM:Register("sound", "|cFFFF00FFRun|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\run.ogg]])
LSM:Register("sound", "|cFFFF00FFRun out|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\run_out.ogg]])
LSM:Register("sound", "|cFFFF00FFRun to edge|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\runtoedge.ogg]])
LSM:Register("sound", "|cFFFF00FFSafe now|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\safe_now.ogg]])
LSM:Register("sound", "|cFFFF00FFSeed|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\seed.ogg]])
LSM:Register("sound", "|cFFFF00FFSelf CD|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\self_cd.ogg]])
LSM:Register("sound", "|cFFFF00FFShield|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\shield.ogg]])
LSM:Register("sound", "|cFFFF00FFShield charge|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\shieldcharge.ogg]])
LSM:Register("sound", "|cFFFF00FFShockwave|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\shockwave.ogg]])
LSM:Register("sound", "|cFFFF00FFSide|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\side.ogg]])
LSM:Register("sound", "|cFFFF00FFSilence soon|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\silencesoon.ogg]])
LSM:Register("sound", "|cFFFF00FFSoak|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\soak.ogg]])
LSM:Register("sound", "|cFFFF00FFSoon|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\soon.ogg]])
LSM:Register("sound", "|cFFFF00FFSpawn|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\spawn.ogg]])
LSM:Register("sound", "|cFFFF00FFSpecial incoming|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\special_incoming.ogg]])
LSM:Register("sound", "|cFFFF00FFSpellsteal|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\spellsteal.ogg]])
LSM:Register("sound", "|cFFFF00FFSplit|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\split.ogg]])
LSM:Register("sound", "|cFFFF00FFSpread|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\spread.ogg]])
LSM:Register("sound", "|cFFFF00FFStack|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stack.ogg]])
LSM:Register("sound", "|cFFFF00FFStack high|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stackhigh.ogg]])
LSM:Register("sound", "|cFFFF00FFStay away from lines|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stayawayfromlines.ogg]])
LSM:Register("sound", "|cFFFF00FFStomp flowers|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stomp_flowers.ogg]])
LSM:Register("sound", "|cFFFF00FFStop attacking|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stop_attacking.ogg]])
LSM:Register("sound", "|cFFFF00FFStop casting|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stop_casting.ogg]])
LSM:Register("sound", "|cFFFF00FFSwap soon|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\swap_soon.ogg]])
LSM:Register("sound", "|cFFFF00FFSwitch|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\switch.ogg]])
LSM:Register("sound", "|cFFFF00FFTake damage|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\take_damage.ogg]])
LSM:Register("sound", "|cFFFF00FFTarget change|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\target_change.ogg]])
LSM:Register("sound", "|cFFFF00FFTargeted|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\targeted.ogg]])
LSM:Register("sound", "|cFFFF00FFTaunt boss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\tauntboss.ogg]])
LSM:Register("sound", "|cFFFF00FFTeleport on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\teleport_you.ogg]])
LSM:Register("sound", "|cFFFF00FFThreat rip|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\threat_rip.ogg]])
LSM:Register("sound", "|cFFFF00FFThrow|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\throw.ogg]])
LSM:Register("sound", "|cFFFF00FFToss incoming|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\toss_incoming.ogg]])
LSM:Register("sound", "|cFFFF00FFToss on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\toss_on_you.ogg]])
LSM:Register("sound", "|cFFFF00FFTotem|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\totem.ogg]])
LSM:Register("sound", "|cFFFF00FFTransporter|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\transporter.ogg]])
LSM:Register("sound", "|cFFFF00FFTrap|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\trap.ogg]])
LSM:Register("sound", "|cFFFF00FFTurn|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\turn.ogg]])
LSM:Register("sound", "|cFFFF00FFUse|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\use.ogg]])
LSM:Register("sound", "|cFFFF00FFUse extra action|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\use_extra_action.ogg]])
LSM:Register("sound", "|cFFFF00FFUse item|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\use_item.ogg]])
LSM:Register("sound", "|cFFFF00FFUse personal|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\use_personal.ogg]])
LSM:Register("sound", "|cFFFF00FFWatch feet|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\watch_feet.ogg]])
LSM:Register("sound", "|cFFFF00FFWatch orb|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\watch_orb.ogg]])
LSM:Register("sound", "|cFFFF00FFWatch wave|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\watch_wave.ogg]])
LSM:Register("sound", "|cFFFF00FFWatch your step|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\watchstep.ogg]])
LSM:Register("sound", "|cFFFF00FFWave|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\wave.ogg]])
LSM:Register("sound", "|cFFFF00FFWhirlwind|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\whirlwind.ogg]])
LSM:Register("sound", "|cFFFF00FFWinds|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\winds.ogg]])
LSM:Register("sound", "|cFFFF00FFYou are targeted|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\you_are_targeted.ogg]])
LSM:Register("sound", "|cFFFF00FFZone|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\zone.ogg]])
