local LSM = LibStub("LibSharedMedia-3.0") 

-- COUNTDOWN
LSM:Register("sound", "BB-|cFFFF00FF1|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\1.ogg]])
LSM:Register("sound", "BB-|cFFFF00FF2|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\2.ogg]])
LSM:Register("sound", "BB-|cFFFF00FF3|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\3.ogg]])
LSM:Register("sound", "BB-|cFFFF00FF4|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\4.ogg]])
LSM:Register("sound", "BB-|cFFFF00FF5|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\5.ogg]])
LSM:Register("sound", "BB-|cFFFF00FF6|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\6.ogg]])
LSM:Register("sound", "BB-|cFFFF00FF7|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\7.ogg]])
LSM:Register("sound", "BB-|cFFFF00FF8|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\8.ogg]])
LSM:Register("sound", "BB-|cFFFF00FF9|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\9.ogg]])
LSM:Register("sound", "BB-|cFFFF00FF10|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\10.ogg]])

-- RAID MARKERS
LSM:Register("sound", "BB-|cFFD2D153Star|r |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\star.ogg]])
LSM:Register("sound", "BB-|cFFD2D153Yellow|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\yellow.ogg]])
LSM:Register("sound", "BB-|cFFD2D153Yellow on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\yellowyou.ogg]])
LSM:Register("sound", "BB-|cFFD2D153Move to yellow|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_yellow.ogg]])
LSM:Register("sound", "BB-|cFFD2D153Move to star|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_star.ogg]])

LSM:Register("sound", "BB-|cFFE17D03Circle|r |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\circle.ogg]])
LSM:Register("sound", "BB-|cFFE17D03Orange|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\orange.ogg]])
LSM:Register("sound", "BB-|cFFE17D03Orange on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\orangeyou.ogg]])
LSM:Register("sound", "BB-|cFFE17D03Move to orange|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_orange.ogg]])
LSM:Register("sound", "BB-|cFFE17D03Move to circle|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_circle.ogg]])

LSM:Register("sound", "BB-|cFFCA4AD5Diamond|r |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\diamond.ogg]])
LSM:Register("sound", "BB-|cFFCA4AD5Purple|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\purple.ogg]])
LSM:Register("sound", "BB-|cFFCA4AD5Purple on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\purpleyou.ogg]])
LSM:Register("sound", "BB-|cFFCA4AD5Move to purple|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_purple.ogg]])
LSM:Register("sound", "BB-|cFFCA4AD5Move to diamond|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_diamond.ogg]])

LSM:Register("sound", "BB-|cFF20B717Triangle|r |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\triangle.ogg]])
LSM:Register("sound", "BB-|cFF20B717Green|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\green.ogg]])
LSM:Register("sound", "BB-|cFF20B717Green on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\greenyou.ogg]])
LSM:Register("sound", "BB-|cFF20B717Move to green|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_green.ogg]])
LSM:Register("sound", "BB-|cFF20B717Move to triangle|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_triangle.ogg]])

LSM:Register("sound", "BB-|cFF02BEE9Square|r |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\square.ogg]])
LSM:Register("sound", "BB-|cFF02BEE9Blue|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\blue.ogg]])
LSM:Register("sound", "BB-|cFF02BEE9Blue on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\blueyou.ogg]])
LSM:Register("sound", "BB-|cFF02BEE9Move to blue|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_blue.ogg]])
LSM:Register("sound", "BB-|cFF02BEE9Move to square|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_square.ogg]])

LSM:Register("sound", "BB-|cFFEC5B41Cross|r |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cross.ogg]])
LSM:Register("sound", "BB-|cFFEC5B41Red|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\red.ogg]])
LSM:Register("sound", "BB-|cFFEC5B41Red on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\redyou.ogg]])
LSM:Register("sound", "BB-|cFFEC5B41Move to red|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_red.ogg]])
LSM:Register("sound", "BB-|cFFEC5B41Move to cross|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_cross.ogg]])

LSM:Register("sound", "BB-|CFFD5F9FASkull|r |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\skull.ogg]])
LSM:Register("sound", "BB-|CFFD5F9FAMove to skull|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_skull.ogg]])

LSM:Register("sound", "BB-|CFFD5F9FAMoon|r |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\moon.ogg]])
LSM:Register("sound", "BB-|CFFD5F9FAMove to moon|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_moon.ogg]])


-- CARDINAL DIRECTIONS
LSM:Register("sound", "BB-|cFFFF00FFNorth|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\north.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFEast|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\east.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSouth|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\south.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFWest|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\west.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFNortheast|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\northeast.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFNorthwest|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\northwest.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSoutheast|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\southeast.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSouthwest|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\southwest.ogg]])


-- RELATIVE DIRECTIONS
LSM:Register("sound", "BB-|cFFFF00FFLeft|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\left.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFRight|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\right.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCenter|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\center.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCenter left|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\center_left.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCenter right|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\center_right.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFFront|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\front.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFFront left|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\front_left.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFFront right|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\front_right.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBack|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\back.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBack left|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\back_left.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBack right|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\back_right.ogg]])

-- GROUPINGS
LSM:Register("sound", "BB-|cFFFF00FFGroup 1|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\group1.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFGroup 2|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\group2.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFGroup 3|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\group3.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFGroup 4|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\group4.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFGroup 5|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\group5.ogg]])

LSM:Register("sound", "BB-|cFFFF00FFInterrupt 1|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt_1.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFInterrupt 2|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt_2.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFInterrupt 3|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt_3.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFInterrupt 4|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt_4.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFInterrupt 5|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt_5.ogg]])

-- PHASES
LSM:Register("sound", "BB-|cFFFF00FFPhase 1|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\phase_one.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPhase 2|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\phase_two.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPhase 3|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\phase_three.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPhase 4|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\phase_four.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPhase 5|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\phase_five.ogg]])

LSM:Register("sound", "BB-|cFFFF00FFIntermission|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\intermission.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPhase change|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\phase_change.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSwitch Phase|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\switch_phase.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFTransition|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\transition.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFTransition phase|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\transition_phase.ogg]])

-- DPS Timings
LSM:Register("sound", "BB-|cFFFF00FFDPS - Hard|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dpshard.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDPS - More|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dpsmore.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDPS - Slow|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dpsslow.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDPS - Stop|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dpsstop.ogg]])

-- Common instructions
LSM:Register("sound", "BB-|cFFFF00FFStop|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stop.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFGo|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\go.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFIn|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\in.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFOut|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\out.ogg]])

-- EVERYTHING ELSE, ALPHABETICAL (except for acronyms)
LSM:Register("sound", "BB-|cFFFF00FFAdd|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\add.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFAdds|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\adds.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFAffix|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\affix.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFAdds Incoming|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\adds_incoming.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFAOE|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\aoe.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFAssist|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\assist.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFAvoid|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\avoid.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFArtillery|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\artillery.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFAttack totem|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\attack_totem.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBack|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\back.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBack up|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\back_up.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBait|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\bait.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBehind Boss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\behind_boss.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBig Add|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\big_add.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBlaze|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\blaze.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBleed|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\bleed.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBlessing of sacrifice|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\blessing_of_sacrifice.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSac|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\sac.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBloodlust|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\bloodlust.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBomb on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\bombyou.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBoss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\boss.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBreak|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\break.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBreak chain|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\breakchain.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBreak LOS|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\breaklos.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBreath incoming|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\breath_incoming.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFBuff|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\buff.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCage|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cage.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCatch balls|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\catch_balls.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCrowd control|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\crowdcontrol.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCrowd control (CC)|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cc.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCooldown|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cooldown.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCooldown (CD)|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cd.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFChain|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\chain.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFChange color|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\change_color.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCharge|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\charge.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCharging move|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\charging_move.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFClear|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\clear.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCleave|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cleave.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCollect|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\collect.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCrusher|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\crusher.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFCurse|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\curse.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDance|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dance.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDanger close|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\danger_close.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDebuff|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\debuff.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDebuff on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\debuffyou.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDefensive|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\defensive.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDemolisher|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\demolisher.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDisease|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\disease.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDispel|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dispel.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDispel boss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dispel_boss.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDodge|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dodge.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDon\'t|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dont.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDon\'t move|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dont_move.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDoT|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dot.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFDrop|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\drop.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFEnfeebling roar|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\enfeebling_roar.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFEnrage|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\enrage.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFEnter|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\enter.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFEscort|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\escort.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFExit|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\exit.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFFear incoming|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\fear_incoming.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFFeet|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\feet.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFFind shelter|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\find_shelter.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFFind shield|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\find_shield.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFFixate|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\fixate.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFFocus|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\focus.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFFrenzy|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\frenzy.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFFrontal|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\frontal.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFGate|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\gate.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFGather|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\gather.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFGather item|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\gather_item.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFHealthstone|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\healthstone.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFHeal to full|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\heal_to_full.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFHeal CD|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\healcd.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFHealing Cooldown|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\healing_cooldown.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFHelp soak|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\help_soak.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFHelp spirit|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\help_spirit.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFHeroism|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\heroism.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFHide|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\hide.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFHigh energy|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\high_energy.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFHigh stacks|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\high_stacks.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFImmunity|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\immunity.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFIncoming debuff|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\incoming_debuff.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFInnervate|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\innervate.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFInterrupt|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFInvisibility|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\invisibility.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFJump|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\jump.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFJump now|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\jump_now.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFJust don\'t|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\just_dont.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFKeep jumping|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\keep_jumping.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFKeep moving|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\keep_moving.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFKick|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\kick.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFKill big add|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\kill_big_add.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFKite|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\kite.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFKnock|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\knock.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFKnockback|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\knockback.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFLaser on you, run|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\laser_run.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFLine apart|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\line_apart.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFLine gather|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\line_gather.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFLine of Sight|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\line_of_sight.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFLine on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\lineyou.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFLinked|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\linked.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFLow health|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\low_health.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMacro|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\macro.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMagic|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\magic.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMain|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\main.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMarked for death|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\marked_for_death.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMind control|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\mindcontrol.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMind control (MC)|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\mc.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMelee|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\melee.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMeteor run|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\meteorrun.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMove boss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_boss.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMove to boss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_boss.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMove to egg|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\movetoegg.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMove to melee|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_melee.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMove to mobs|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_mobs.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMove to pillar|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_pillar.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMove to pool|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_pool.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMove to statue|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\movetostatue.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMove to tank|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move_to_tank.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFMove to web|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\movetoweb.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFNegative|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\negative.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFNext|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\next.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFNuke|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\nuke.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFOrb|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\orb.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFOverlap|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\overlap.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPain Suppression|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pain_suppression.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPain Suppression (PS)|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\ps.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFParanoia on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\paranoiayou.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPass Debuff|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pass_debuff.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPersonal CD|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\personal_cd.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPhysical|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\physical.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPower Infusion|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\power_infusion.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPower Infusion (PI)|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pi.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPoison|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\poison.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPolarity shift|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\polarity_shift.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPositive|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\positive.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPotions|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\potions.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPots|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pots.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPull|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pull.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPull adds out|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pull_adds_out.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPulling in|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pulling_in.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPulverize|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pulverize.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPush|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\push.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFPushback incoming|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pushback_incoming.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFQuake|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\quake.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFRange|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\range.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFRage on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\rageyou.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFRange 5|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\range5.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFReady|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\ready.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFReady to interrupt|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\ready_interrupt.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFReflect|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\reflect.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFRefresh|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\refresh.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFRing|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\ring.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFRoot|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\root.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFRun|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\run.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFRun out|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\run_out.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFRun to edge|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\runtoedge.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSafe now|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\safe_now.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSeed|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\seed.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSelf CD|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\self_cd.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFShield|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\shield.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFShield charge|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\shield_charge.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFShockwave|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\shockwave.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSide|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\side.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSilence soon|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\silence_soon.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSoak|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\soak.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSoon|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\soon.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSpawn|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\spawn.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSpecial incoming|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\special_incoming.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSpellsteal|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\spellsteal.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSplit|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\split.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSpread|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\spread.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFStack|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stack.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFStack high|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stackhigh.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFStay away from lines|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stay_away_from_lines.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFStomp flowers|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stomp_flowers.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFStop attacking|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stop_attacking.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFStop casting|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stop_casting.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFStop charge with line|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stopchargewithline.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSwap soon|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\swap_soon.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFSwitch|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\switch.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFTake damage|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\take_damage.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFTarget change|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\target_change.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFTargeted|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\targeted.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFTaunt boss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\taunt_boss.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFTeleport on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\teleport_you.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFThreat rip|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\threat_rip.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFThrow|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\throw.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFToss incoming|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\toss_incoming.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFToss on you|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\toss_on_you.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFTotem|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\totem.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFTransporter|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\transporter.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFTrap|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\trap.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFTurn|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\turn.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFUse|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\use.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFUse extra action|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\use_extra_action.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFUse item|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\use_item.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFUse personal|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\use_personal.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFWatch feet|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\watch_feet.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFWatch orb|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\watch_orb.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFWatch wave|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\watch_wave.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFWatch your step|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\watch_step.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFWave|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\wave.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFWhirlwind|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\whirlwind.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFWinds|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\winds.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFYou are targeted|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\you_are_targeted.ogg]])
LSM:Register("sound", "BB-|cFFFF00FFZone|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\zone.ogg]])

-- Duplication to cover Dungeon/Raid Packs utilizing Causese lines
LSM:Register("sound", "|cFFFF00001|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\1.ogg]])
LSM:Register("sound", "|cFFFF00002|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\2.ogg]])
LSM:Register("sound", "|cFFFF00003|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\3.ogg]])
LSM:Register("sound", "|cFFFF00004|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\4.ogg]])
LSM:Register("sound", "|cFFFF00005|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\5.ogg]])
LSM:Register("sound", "|cFFFF00006|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\6.ogg]])
LSM:Register("sound", "|cFFFF00007|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\7.ogg]])
LSM:Register("sound", "|cFFFF00008|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\8.ogg]])
LSM:Register("sound", "|cFFFF00009|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\9.ogg]])
LSM:Register("sound", "|cFFFE000010|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\10.ogg]])

LSM:Register("sound", "|cFFFF00001. First|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\First.ogg]])
LSM:Register("sound", "|cFFFF00002. Second|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\Second.ogg]])
LSM:Register("sound", "|cFFFF00003. Third|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\Third.ogg]])
LSM:Register("sound", "|cFFFF00004. Fourth|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\Fourth.ogg]])
LSM:Register("sound", "|cFFFF00005. Fifth|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\Fifth.ogg]])

LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\star.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\circle.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\diamond.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\triangle.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\moon.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\square.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cross.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|t", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\skull.ogg]])
LSM:Register("sound", "|cFFFF0000Add|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\add.ogg]])
LSM:Register("sound", "|cFFFF0000Adds|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\adds.ogg]])
LSM:Register("sound", "|cFFFF0000Affix|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\affix.ogg]])
LSM:Register("sound", "|cFFFF0000AoE|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\aoe.ogg]])
LSM:Register("sound", "|cFFFF0000Assist|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\assist.ogg]])
LSM:Register("sound", "|cFFFF0000Avoid|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\avoid.ogg]])
LSM:Register("sound", "|cFFFF0000Back|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\back.ogg]])
LSM:Register("sound", "|cFFFF0000Backup|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\backup.ogg]])
LSM:Register("sound", "|cFFFF0000Bait|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\bait.ogg]])
LSM:Register("sound", "|cFFFF0000Beam|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\beam.ogg]])
LSM:Register("sound", "|cFFFF0000Bloodlust|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\bloodlust.ogg]])
LSM:Register("sound", "|cFFFF0000Blue|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\blue.ogg]])
LSM:Register("sound", "|cFFFF0000Boss|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\boss.ogg]])
LSM:Register("sound", "|cFFFF0000Break|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\break.ogg]])
LSM:Register("sound", "|cFFFF0000Buff|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\buff.ogg]])
LSM:Register("sound", "|cFFFF0000CC|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cc.ogg]])
LSM:Register("sound", "|cFFFF0000CD|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\cd.ogg]])
LSM:Register("sound", "|cFFFF0000Center|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\center.ogg]])
LSM:Register("sound", "|cFFFF0000Chain|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\chain.ogg]])
LSM:Register("sound", "|cFFFF0000Charge|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\charge.ogg]])
LSM:Register("sound", "|cFFFF0000Clear|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\clear.ogg]])
LSM:Register("sound", "|cFFFF0000Collect|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\collect.ogg]])
LSM:Register("sound", "|cFFFF0000Dance|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dance.ogg]])
LSM:Register("sound", "|cFFFF0000Defensive|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\defensive.ogg]])
LSM:Register("sound", "|cFFFF0000Debuff|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\debuff.ogg]])
LSM:Register("sound", "|cFFFF0000Dispell|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dispel.ogg]])
LSM:Register("sound", "|cFFFF0000Dodge|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dodge.ogg]])
LSM:Register("sound", "|cFFFF0000Dont|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dont.ogg]])
LSM:Register("sound", "|cFFFF0000Dont Move|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dont_move.ogg]])
LSM:Register("sound", "|cFFFF0000Dot|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\dot.ogg]])
LSM:Register("sound", "|cFFFF0000Drop|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\drop.ogg]])
LSM:Register("sound", "|cFFFF0000Enter|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\enter.ogg]])
LSM:Register("sound", "|cFFFF0000Escort|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\escort.ogg]])
LSM:Register("sound", "|cFFFF0000Exit|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\exit.ogg]])
LSM:Register("sound", "|cFFFF0000Feet|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\feet.ogg]])
LSM:Register("sound", "|cFFFF0000Fixate|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\fixate.ogg]])
LSM:Register("sound", "|cFFFF0000Focus|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\focus.ogg]])
LSM:Register("sound", "|cFFFF0000Front|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\front.ogg]])
LSM:Register("sound", "|cFFFF0000Gate|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\gate.ogg]])
LSM:Register("sound", "|cFFFF0000Gather|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\gather.ogg]])
LSM:Register("sound", "|cFFFF0000Green|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\green.ogg]])
LSM:Register("sound", "|cFFFF0000Go|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\go.ogg]])
LSM:Register("sound", "|cFFFF0000Healcd|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\healcd.ogg]])
LSM:Register("sound", "|cFFFF0000Hide|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\hide.ogg]])
LSM:Register("sound", "|cFFFF0000High Energy|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\high_energy.ogg]])
LSM:Register("sound", "|cFFFF0000High Stacks|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\high_stacks.ogg]])
LSM:Register("sound", "|cFFFF0000Immunity|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\immunity.ogg]])
LSM:Register("sound", "|cFFFF0000In|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\in.ogg]])
LSM:Register("sound", "|cFFFF0000Interrupt|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\interrupt.ogg]])
LSM:Register("sound", "|cFFFF0000Intermission|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\intermission.ogg]])
LSM:Register("sound", "|cFFFF0000Invisibility|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\invisibility.ogg]])
LSM:Register("sound", "|cFFFF0000Jump|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\jump.ogg]])
LSM:Register("sound", "|cFFFF0000Kick|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\kick.ogg]])
LSM:Register("sound", "|cFFFF0000Kite|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\kite.ogg]])
LSM:Register("sound", "|cFFFF0000Knock|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\knock.ogg]])
LSM:Register("sound", "|cFFFF0000Left|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\left.ogg]])
LSM:Register("sound", "|cFFFF0000Linked|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\linked.ogg]])
LSM:Register("sound", "|cFFFF0000LoS|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\line_of_sight.ogg]])
LSM:Register("sound", "|cFFFF0000Macro|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\macro.ogg]])
LSM:Register("sound", "|cFFFF0000Melee|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\melee.ogg]])
LSM:Register("sound", "|cFFFF0000Move|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\move.ogg]])
LSM:Register("sound", "|cFFFF0000Next|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\next.ogg]])
LSM:Register("sound", "|cFFFF0000Nuke|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\nuke.ogg]])
LSM:Register("sound", "|cFFFF0000Orange|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\orange.ogg]])
LSM:Register("sound", "|cFFFF0000Orb|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\orb.ogg]])
LSM:Register("sound", "|cFFFF0000Out|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\out.ogg]])
LSM:Register("sound", "|cFFFF0000Overlap|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\overlap.ogg]])
LSM:Register("sound", "|cFFFF0000Pots|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pots.ogg]])
LSM:Register("sound", "|cFFFF0000Pull|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\pull.ogg]])
LSM:Register("sound", "|cFFFF0000Purple|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\purple.ogg]])
LSM:Register("sound", "|cFFFF0000Push|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\push.ogg]])
LSM:Register("sound", "|cFFFF0000Range|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\range.ogg]])
LSM:Register("sound", "|cFFFF0000Ready|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\ready.ogg]])
LSM:Register("sound", "|cFFFF0000Red|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\red.ogg]])
LSM:Register("sound", "|cFFFF0000Reflect|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\reflect.ogg]])
LSM:Register("sound", "|cFFFF0000Refresh|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\refresh.ogg]])
LSM:Register("sound", "|cFFFF0000Right|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\right.ogg]])
LSM:Register("sound", "|cFFFF0000Ring|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\ring.ogg]])
LSM:Register("sound", "|cFFFF0000Root|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\root.ogg]])
LSM:Register("sound", "|cFFFF0000Seed|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\seed.ogg]])
LSM:Register("sound", "|cFFFF0000Selfcd|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\self_cd.ogg]])
LSM:Register("sound", "|cFFFF0000Shield|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\shield.ogg]])
LSM:Register("sound", "|cFFFF0000Soak|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\soak.ogg]])
LSM:Register("sound", "|cFFFF0000Soon|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\soon.ogg]])
LSM:Register("sound", "|cFFFF0000Spawn|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\spawn.ogg]])
LSM:Register("sound", "|cFFFF0000Spellsteal|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\spellsteal.ogg]])
LSM:Register("sound", "|cFFFF0000Split|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\split.ogg]])
LSM:Register("sound", "|cFFFF0000Spread|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\spread.ogg]])
LSM:Register("sound", "|cFFFF0000Stack|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stack.ogg]])
LSM:Register("sound", "|cFFFF0000Stop|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stop.ogg]])
LSM:Register("sound", "|cFFFF0000Stopcast|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\stop_casting.ogg]])
LSM:Register("sound", "|cFFFF0000Switch|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\switch.ogg]])
LSM:Register("sound", "|cFFFF0000Targeted|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\targeted.ogg]])
LSM:Register("sound", "|cFFFF0000Taunt|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\taunt.ogg]])
LSM:Register("sound", "|cFFFF0000Totem|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\totem.ogg]])
LSM:Register("sound", "|cFFFF0000Transition|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\transition.ogg]])
LSM:Register("sound", "|cFFFF0000Trap|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\trap.ogg]])
LSM:Register("sound", "|cFFFF0000Turn|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\turn.ogg]])
LSM:Register("sound", "|cFFFF0000Use|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\use.ogg]])
LSM:Register("sound", "|cFFFF0000Winds|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\winds.ogg]])
LSM:Register("sound", "|cFFFF0000Yellow|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\yellow.ogg]])
LSM:Register("sound", "|cFFFF0000Zone|r", [[Interface\Addons\sharedmedia-battlebrisket-vo\sound\zone.ogg]])
